Tetris1:
    env_id: tetris_gymnasium/Tetris
    hidden_layer_dim: 32
    num_episodes: 2500
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.999
    learning_rate: 0.005
    discount_factor: 0.85
TetrisReplay:
    env_id: tetris_gymnasium/Tetris
    hidden_layer_dim: 256
    num_episodes: 2500
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.9999
    learning_rate: 0.001
    discount_factor: 0.85
    replay_buffer_size: 100000
    batch_size: 32
    target_update_freq: 10
TetrisRandom:
    env_id: tetris_gymnasium/Tetris
    hidden_layer_dim: 256
    num_episodes: 2500
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.9999
    learning_rate: 0.001
    discount_factor: 0.85
    replay_buffer_size: 100000
    batch_size: 32
    target_update_freq: 10
